/*
 * Copyright (c) 2012 Citrix Systems, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XenGuestAgent.rc
//
#define IDS_SERVICENAME                 100
#define IDR_XENGUESTAGENT               101
#define IDR_XENGUESTSERVICES            102
#define IDS_XENWIRELESS                 103
#define IDR_XENVMINFO                   104
#define IDS_DISPLAYNAME                 200
#define IDS_SERVICEDESC                 201
#define IDI_ICON1                       201
#define IDS_ATLBASE_NO_HANDLER          401
#define IDS_ATLBASE_SERVICE_STOPPED     402
#define IDS_ATLBASE_SERVICE_STARTED     403
#define IDS_ATLBASE_BAD_SERVICE         404

#define IDS_FAILED_TO_CREATE_OBJECT_LOCK___H_XENGUESTSERVICES_24         4000
#define IDS_FAILED_TO_OPEN_XENSTORE___HRESUL_XENGUESTSERVICES_32         4001
#define IDS_FAILED_TO_INITIALIZE_VM_VALUES___XENGUESTSERVICES_53         4002
#define IDS_MAXIMUM_INSTANCE_COUNT_REACHED___XENGUESTSERVICES_61         4003
#define IDS_FAILED_TO_CREATE_VMS_EVENT_GUID__XENGUESTSERVICES_474        4004
#define IDS_FAILED_TO_CREATE_VMS_EVENT___HRE_XENGUESTSERVICES_492        4005
#define IDS_FAILED_TO_CREATE_ALERTS_EVENT_GU_XENGUESTSERVICES_532        4006
#define IDS_FAILED_TO_CREATE_ALERTS_EVENT____XENGUESTSERVICES_550        4007
#define IDS_PRINCIPAL__zS_PERMISSION__zS_OPE_XENSECURITYHELPER_35        4008
#define IDS_DENY_CHECK_FAILURE___PERMISSION__XENSECURITYHELPER_1244      4009
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_XENSECURITYHELPER_1279      4010
#define IDS_ACCESSPERMISSION_XENSECURITYHELPER_1281                      4011
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_XENSECURITYHELPER_1301      4012
#define IDS_LAUNCHPERMISSION_LAUNCH_XENSECURITYHELPER_1303               4013
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_XENSECURITYHELPER_1309      4014
#define IDS_LAUNCHPERMISSION_ACTIVATE_XENSECURITYHELPER_1311             4015
#define IDS_DENY_CHECK_FOUND_NO_SD_DACL_FOR__XENSECURITYHELPER_1431      4016
#define IDS_ACCESSPERMISSION_XENSECURITYHELPER_1433                      4017
#define IDS_DENY_CHECK_FOUND_NO_SD_DACL_FOR__XENSECURITYHELPER_1476      4018
#define IDS_LAUNCHPERMISSION_XENSECURITYHELPER_1478                      4019
#define IDS_FAILED_TO_ALLOCATE_SECURITY_ATTR_XENSECURITYHELPER_1559      4020
#define IDS_FAILED_TO_CREATE_SECURITY_DESCRI_XENSECURITYHELPER_1569      4021
#define IDS_FAILED_TO_GET_SIZES_FROM_MAKEABS_XENSECURITYHELPER_1614      4022
#define IDS_FAILED_TO_ALLOCATE_SECURITY_DESC_XENSECURITYHELPER_1625      4023
#define IDS_FAILED_CREATE_SD_IN_MAKEABSOLUTE_XENSECURITYHELPER_1644      4024
#define IDS_FAILED_TO_ALLOCATE_XSH_DESCRIPTO_XENSECURITYHELPER_1689      4025
#define IDS_FAILED_TO_INITIALIZE_COM_SID___E_XENSECURITYHELPER_1699      4026
#define IDS_FAILED_TO_ALLOCATE_PINTERACTIVSI_XENSECURITYHELPER_1709      4027
#define IDS_FAILED_TO_ALLOCATE_ADMINS_SID_XENSECURITYHELPER_1718         4028
#define IDS_FAILED_CREATEWELLKNOWNSID_PINTER_XENSECURITYHELPER_1727      4029
#define IDS_FAILED_CREATEWELLKNOWNSID_PADMIN_XENSECURITYHELPER_1736      4030
#define IDS_FAILED_SETENTRIESINACL_PINTERACT_XENSECURITYHELPER_1755      4031
#define IDS_FAILED_TO_SET_ADMINS_SID_AS_OWNE_XENSECURITYHELPER_1765      4032
#define IDS_FAILED_TO_SET_ADMINS_SID_AS_GROU_XENSECURITYHELPER_1773      4033
#define IDS_FAILED_TO_SET_DACL_FOR_SD___ERRO_XENSECURITYHELPER_1782      4034
#define IDS_FAILED_TO_CONNECT_TO_BACKEND___E_XENHTTP_213                 4035
#define IDS_ATTEMPTING_TO_REUSE_CXENHTTP_WIT_XENHTTP_292                 4036
#define IDS_FAILED_TO_SEND_zS___ERROR__zD_XENHTTP_327                    4037
#define IDS_FAILED_TO_SEND_zS___NOT_ALL_DATA_XENHTTP_334                 4038
#define IDS_FAILED_TO_SEND_zS_DATA___ERROR___XENHTTP_354                 4039
#define IDS_FAILED_TO_SEND_zS_DATA___NOT_ALL_XENHTTP_361                 4040
#define IDS_zS_HEADER_TIMEOUT_AFTER_zD_MS_XENHTTP_385                    4041
#define IDS_FAILURE_DURING_WAITFORMULTIPLEOB_XENHTTP_393                 4042
#define IDS_FAILED_TO_READ_zS_HEADER___ERROR_XENHTTP_408                 4043
#define IDS_FAILED_TO_READ_zS_HEADER___NO_DA_XENHTTP_415                 4044
#define IDS_FAILED_TO_PROCESS_zS_RESPONSE____XENHTTP_425                 4045
#define IDS_INVALID_CONTENT_LENGTH_SPECIFIED_XENHTTP_437                 4046
#define IDS_SAFEARRAYACCESSDATA___FAILED___H_XENHTTP_452                 4047
#define IDS_zS_DATA_TIMEOUT_AFTER_zD_MS_XENHTTP_476                      4048
#define IDS_FAILURE_DURING_WAITFORMULTIPLEOB_XENHTTP_485                 4049
#define IDS_FAILED_TO_READ_zS_DATA___ERROR___XENHTTP_499                 4050
#define IDS_FAILED_TO_READ_zS_DATA___NO_DATA_XENHTTP_506                 4051
#define IDS_CRITICAL_FAILURE___zS_VALUE_READ_XENHTTP_514                 4052
#define IDS_SETUPPARAMETERKEY_COULD_NOT_CREA_XENGUESTAGENT_106           4053
#define IDS_SETUPPARAMETERKEY_COULD_NOT_SET__XENGUESTAGENT_115           4054
#define IDS_SETUPPARAMETERKEY_COULD_NOT_SET__XENGUESTAGENT_123           4055
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_OP_XENGUESTAGENT_145           4056
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_CR_XENGUESTAGENT_155           4057
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_SE_XENGUESTAGENT_165           4058
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_SE_XENGUESTAGENT_176           4059
#define IDS_UNREGISTEREVENTSOURCE_COULD_NOT__XENGUESTAGENT_193           4060
#define IDS_UPDATESERVICEREGISTRY_COULD_NOT__XENGUESTAGENT_233           4061
#define IDS_UPDATESERVICEREGISTRY_COULD_NOT__XENGUESTAGENT_244           4062
#define IDS_UPDATESERVICEREGISTRY_CHANGE_SER_XENGUESTAGENT_264           4063
#define IDS_UPDATESERVICEREGISTRY_CHANGE_SER_XENGUESTAGENT_275           4064
#define IDS_FAILED_TO_LOAD_XS2_LIBRARY___ERR_XENGUESTAGENT_413           4065
#define IDS_FAILED_TO_START__SERVICE_SHOULD__XENGUESTAGENT_439           4066
#define IDS_FAILED_TO_START_SERVICE_XENGUESTAGENT_459                    4067
#define IDS_GETVERSIONEX_FAILED_____ERROR__z_XENGUESTAGENT_537           4068
#define IDS_FAILED_TO_CREATE_SHUTDOWN_EVENT__XENGUESTAGENT_545           4069
#define IDS_FAILED_TO_CREATE_VMS_EVENT___ERR_XENGUESTAGENT_553           4070
#define IDS_FAILED_TO_CREATE_VMS_VECTOR_LOCK_XENGUESTAGENT_561           4071
#define IDS_FAILED_TO_CREATE_ALERTS_VECTOR_L_XENGUESTAGENT_569           4072
#define IDS_XS2OPEN_FAILED_FOR_START__NOT_RU_XENGUESTAGENT_689           4073
#define IDS_XS2READ_FAILED_FOR_VM___ERROR__z_XENGUESTAGENT_697           4074
#define IDS_XS2READ_FAILED_FOR_VM___ERROR__z_XENGUESTAGENT_720           4075
#define IDS_FAILED_TO_START_TASK_THREAD___ER_XENGUESTAGENT_730           4076
#define IDS_FAILED_TO_START_VMS_WATCH_THREAD_XENGUESTAGENT_739           4077
#define IDS_FAILED_TO_START_ALERTS_WATCH_THR_XENGUESTAGENT_748           4078
#define IDS_XS2OPEN_FAILED_FOR_LOADVMS___ERR_XENGUESTAGENT_1090          4079
#define IDS_XS2DIRECTORY_NO_VMS_RETURNED____XENGUESTAGENT_1101           4080
#define IDS_FAILED_TO_RETURN_SYSTEM_DIRECTOR_XENGUESTAGENT_1248          4081
#define IDS_FAILED_TO_LAUNCH_POWERCFG_TOOL___XENGUESTAGENT_1261          4082
#define IDS_FAILURE_RETURNED_FROM_POWEROPTS__XENGUESTAGENT_1282          4083
#define IDS_WLANPROF__WLANAPI_DLL_NOT_FOUND_XENGUESTAGENT_1302           4084
#define IDS_WLANPROF__ERROR_LOADING_WIFI_API_XENGUESTAGENT_1306          4085
#define IDS_WLANPROF__ERROR_GETTING_LIST_OF__XENGUESTAGENT_1310          4086
#define IDS_WLANPROF__ERROR_ADDING_AP__WLAN__XENGUESTAGENT_1314          4087
#define IDS_WLANPROF__UNKNOWN_FAILURE_ENCOUN_XENGUESTAGENT_1318          4088
#define IDS_XS2OPEN_FAILED_FOR_WATCHES___ERR_XENGUESTAGENT_1339          4089
#define IDS_FAILED_TO_OPEN_XENSTORE_VMS_WATC_XENGUESTAGENT_1349          4090
#define IDS_XS_WATCH_THREAD_SHUTTING_DOWN__XENGUESTAGENT_1359            4091
#define IDS_WAIT_FAILED_DURING_XS_WATCH_WAIT_XENGUESTAGENT_1370          4092
#define IDS_UNKNOWN_FAILURE_DURING_XS_WATCH__XENGUESTAGENT_1378          4093
#define IDS_RECEIVED_XCDIAG_REQUEST_XENGUESTAGENT_1414                   4094
#define IDS_FAILED_TO_LAUNCH_XCDIAG_TOOL___E_XENGUESTAGENT_1430          4095
#define IDS_FAILED_TO_OPEN_XCDIAG_OUTPUT_FIL_XENGUESTAGENT_1465          4096
#define IDS_XCDIAG_OUTPUT_FILE_APPEARS_EMPTY_XENGUESTAGENT_1476          4097
#define IDS_FAILED_TO_ALLOCATE_MEMORY_FOR_XC_XENGUESTAGENT_1486          4098
#define IDS_FAILED_TO_ACCESS_XCDIAG_FILE_XENGUESTAGENT_1502              4099
#define IDS_FAILED_TO_VIEW_XCDIAG_OUTPUT_XENGUESTAGENT_1520              4100
#define IDS_XCDIAG_ZIP_FILE_SENT__XENGUESTAGENT_1591                     4101
#define IDS_DOPOST___OPERATION_FAILED___ERRO_XENGUESTAGENT_1596          4102
#define IDS_DOGET___FAILED_TO_REGISTER_FOR_A_XENGUESTAGENT_1652          4103
#define IDS_FAILED_TO_OPEN_V4V_CHANNEL_ON_FI_XENGUESTAGENT_1721          4104
#define IDS_FAILED_TO_PARSE_JSON_SIGNAL___ER_XENGUESTAGENT_1759          4105
#define IDS_SAFEARRAYACCESSDATA___FAILED___H_XENGUESTAGENT_1800          4106
#define IDS_ALERTS_THREAD_SHUTTING_DOWN__XENGUESTAGENT_1825              4107
#define IDS_DOGET___FAILED_TO_RECEIVE_SIGNAL_XENGUESTAGENT_1831          4108
#define IDS_FAILED_TO_RESET_SIGNAL_REGISTRAT_XENGUESTAGENT_1838          4109
#define IDS_SAFEARRAYCOPY___FAILED___HRESULT_XENGUESTAGENT_1875          4110
#define IDS_E_OUTOFMEMORY___HRESULT__0XzX_XENGUESTAGENT_1881             4111
#define IDS_SAFEARRAYACCESSDATA___FAILED___H_XENGUESTSERVICES_230        4112
#define IDS_SAFEARRAYACCESSDATA___RETRIEVED__XENGUESTSERVICES_237        4113
#define IDS_XS_WATCH_THREAD_SHUTTING_DOWN__XENGUESTSERVICES_301          4114
#define IDS_DOGET___FAILED___ERROR__zD_HTTP__XENGUESTSERVICES_308        4115
#define IDS_COCREATEINSTANCE_CLSID_XENVMINFO_XENGUESTSERVICES_378        4116
#define IDS_QUERYINTERFACE_IXENVMINITIALIZE__XENGUESTSERVICES_385        4117
#define IDS_QUERYINTERFACE_IXENVMINITIALIZE__XENGUESTSERVICES_391        4118
#define IDS_LOADIMAGEUID_FAILED__IMAGE__zS___XENGUESTSERVICES_406        4119
#define IDS_DELETING_XCIPLUGIN_RUN_VALUE_FAI_XENGUESTSERVICES_640        4120
#define IDS_CREATING_XCIPLUGIN_RUN_VALUE_FAI_XENGUESTSERVICES_652        4121
#define IDS_FAILED_TO_OPEN_XENINP_FILE_HANDL_XENGUESTSERVICES_674        4122
#define IDS_FAILED_TO_SEND_XENINP_IOCTL_ACCE_XENGUESTSERVICES_683        4123
#define IDS_FAILED_TO_PARSE_JSON_PROPERTY__ER_XENGUESTAGENT              4124
#define IDS_UNEXPECTED_JSON_VALUE__ER_XENGUESTAGENT                      4125
#define IDS_ARRAY                                                        4126
#define IDS_BOOL                                                         4127
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif

#define ctxLS
